name: Check patchfiles against schema

on: [push]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get changed XML files
      id: changed-xmls
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.xml
    - name: xmllint problem matcher
      uses: korelstar/xmllint-problem-matcher@v1.1.0
    - name: Lint info.xml
      uses: ChristophWurst/xmllint-action@master
      with:
        xml-file: ${{ steps.changed-xmls.outputs.all_changed_files}}
        xml-schema-file: ./schema.xsd
