name: Validate all XMLs once the schema changes

on: 
  push:
    paths:
      - 'schema.xsd'

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get all XML files
      id: list-xmls
      uses: mirko-felice/list-files-action@v3.0.5
      with:
        repo: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: "."
        ext: ".xml"
    - name: xmllint problem matcher
      uses: korelstar/xmllint-problem-matcher@v1.1.0
    - name: Lint info.xml
      uses: ChristophWurst/xmllint-action@master
      with:
        xml-file: ${{ steps.list-files.outputs.paths }}
        xml-schema-file: ./schema.xsd
